---
# Experiment configuration
batch_size: 1
test_batch_size: 1
max_iteration: 100000
lr: 0.001
load: False
cuda: True
shuffle: True
gamma: 0.999
dir_checkpoint: 'checkpoints'

# Model setting
use_usersim: True
num_emotion: 4
num_user_action: 3
max_rounds: 16
update_steps: 1
action_shape: 6
hidden_shape: 24

# Path setting
log_path: 'logs/log.txt'
dqn_log_path: 'logs/dqn_log.txt'
checkpoint_path: 'checkpoint'
